### ISSUE TITLE
Issue with PropTypes

### ISSUE THREAD

**Issue by zog** [calintamas/react-native-toast-message#197]
I'm using your (awesome) package in an expo project.
Everything works fine, except for my unit tests.
When I run `jest`, I get the following error:
```
 TypeError: Cannot read property 'oneOfType' of undefined

      at Object.<anonymous> (node_modules/react-native-toast-message/src/utils/prop-types.js:3:33)
      at Object.<anonymous> (node_modules/react-native-toast-message/src/index.js:3:1)
```
 
It seems that your filename `utils/prop-types.js` is colliding with the `prop-types` package name.

Workaround: Renaming `utils/prop-types.js` to `utils/style-prop-types.js` seems to fix the issue.

**Comment by zog** [comment]
Was a misconfiguration on my side, my bad
